# Generated by Django 3.0.4 on 2020-04-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='tojen',
            new_name='token',
        ),
    ]
